-- AlgoRhythm; DDL
USE AlgoRhythmDB;
GO

CREATE TABLE Health_Insurance_Data_Table (
    PERIDNUM int primary key IDENTITY(1,1),
    PEHSPNON bigint NULL,
    PH_SEQ bigint NULL,
    AGE1 bigint NULL,
    PEAFEVER bigint NULL,
    A_HGA bigint NULL,
    A_SEX bigint NULL,
    PEDISDRS bigint NULL,
    PEDISEAR bigint NULL,
    PEDISEYE bigint NULL,
    PEDISOUT bigint NULL,
    PEDISPHY bigint NULL,
    PEDISREM bigint NULL,
    PRDISFLG bigint NULL,
    PRDTRACE bigint NULL,
    A_MJIND bigint NULL,
    A_GRSWK bigint NULL,
    A_HRSPAY bigint NULL,
    A_CLSWKR bigint NULL,
    A_WKSTAT bigint NULL,
    PEARNVAL bigint NULL,
    PTOTVAL bigint NULL,
    AGI bigint NULL,
    PERLIS bigint NULL,
    COV bigint NULL,
    COV_CYR bigint NULL,
    PUB bigint NULL,
    PUB_CYR bigint NULL,
    DEPPRIV bigint NULL,
    GRP bigint NULL,
    DIR bigint NULL,
    MRK bigint NULL,
    NONM bigint NULL,
    CAID bigint NULL,
    OTHMT bigint NULL,
    MCARE bigint NULL,
    MIL bigint NULL,
    CHAMPVA bigint NULL,
    VACARE bigint NULL,
    MOOP bigint NULL,
    MOOP2 bigint NULL,
    PEMCPREM bigint NULL,
    PHIP_VAL bigint NULL,
    POTC_VAL bigint NULL,
    PMED_VAL bigint NULL,
    PHIP_VAL2 bigint NULL,
    PECOULD bigint NULL,
    PEOFFER bigint NULL,
    HEA bigint NULL,
    timestamp bigint NULL,
);

CREATE TABLE Insured_Respondents_by_State (
    StateID int primary key IDENTITY(1,1),
    [State] varchar(20) NOT NULL,
    NumberInsured int NOT NULL,
    NumberUninsured int NOT NULL,
    Total int NOT NULL,
    PercentInsured float NOT NULL,
    PercentUninsured float NOT NULL,
    [Time] int NOT NULL,
);